### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by asqwrd** [actimeo/ng2-i18next#8]
When i try to compile my code the typescript fails because it cannot find typings/index

if I remove the reference at the top of the i18n-directive.d.ts and service file it compiles

**Comment by actimeo** [comment]
I've published an new 0.1.4 version. Is that working?

**Comment by asqwrd** [comment]
Hi still not working i get this error when i run tsc to compile the typescript files

```
> node_modules/ng2-i18next/lib/i18n-directive.d.ts(1,1): error TS6053: File '/var/www/vhosts/ajibade/webdamdb_1467157717/wip/public/node_modules/ng2-i18next/typings/index.d.ts' not found.
> node_modules/ng2-i18next/lib/i18n-service.d.ts(1,1): error TS6053: File '/var/www/vhosts/ajibade/webdamdb_1467157717/wip/public/node_modules/ng2-i18next/typings/index.d.ts' not found.
```

seems like you are no longer including the typings folder in the package so this error occurs because you have 

> `///<reference path="../typings/index.d.ts"/>`

at the top of i18n-directive.d.ts and i18n-service.d.ts files.  Removing it compiles successully for me.

**Comment by actimeo** [comment]
I removed in v0.1.5 these lines from the 2 source files and placed it elsewhere for the module compilation.
Is it working for you now? 

Thanks for your support

**Comment by asqwrd** [comment]
Hi, yes everything compiles now thanks for being on top of this
